CREATE TABLE "BBANK"."DONORS" (
		"USERNAME" VARCHAR(32 OCTETS) NOT NULL, 
		"NAME" VARCHAR(64 OCTETS), 
		"BLOOD_GROUP" CHAR(3 OCTETS), 
		"RESIDENCE" VARCHAR(200 OCTETS), 
		"COMPANY" VARCHAR(128 OCTETS), 
		"ADDRESS" VARCHAR(200 OCTETS), 
		"BIRTHDATE" DATE, 
		"SEX" CHAR(1 OCTETS), 
		"JOB" VARCHAR(128 OCTETS), 
		"SSN" CHAR(11 OCTETS), 
		"MAIL" VARCHAR(128 OCTETS), 
		"ID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE CHANGES 
	COMPRESS NO;

ALTER TABLE "BBANK"."DONORS" ADD CONSTRAINT "PK_BBANK_DONOR" PRIMARY KEY
	("ID");



CREATE TABLE "DEMO"."SIMPLE" (
		"USERNAME" VARCHAR(32 OCTETS) NOT NULL, 
		"NAME" VARCHAR(64 OCTETS), 
		"MAIL" VARCHAR(128 OCTETS), 
		"ID" INTEGER NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE CHANGES 
	COMPRESS NO;

ALTER TABLE "DEMO"."SIMPLE" ADD CONSTRAINT "PK_DEMO_SIMPLE" PRIMARY KEY
	("ID");